version: '0.1'
initialized_at: '2026-02-01'
# =============================================================================
# Project Registry
# Updated: 2026-02-01T23:59:00+00:00 by 周治理 (Governance Officer)
# Verified: StateEngine tests passed (22/22) - 2026-02-01
# =============================================================================
projects:
  DGSF:
    name: "Dynamic Generative SDF Forest"
    type: "asset_pricing_research"
    status: "active"
    owner: "Project Owner"
    created_at: '2026-02-01'
    last_updated: '2026-02-01T23:59:00+00:00'
    
    # Project Scope
    scope:
      description: "Research & develop SDF-based asset pricing model for A-share market"
      objectives:
        - "Implement State Engine and SDF Model"
        - "Build EA Optimizer for portfolio construction"
        - "Expand to full A-share universe (5000+ stocks)"
        - "Achieve reproducible baseline performance"
    
    # Current Phase
    phase:
      current: "Phase 1 - SDF Layer Development"
      next: "Phase 2 - EA Layer Development"
      stages_completed:
        - "Stage 0: Research & Triage"
        - "Stage 1: Spec Integration"
        - "Stage 1.1: StateEngine Implementation (VERIFIED)"
    
    # Active Tasks
    active_tasks:
      - task_id: "SDF_DEV_001"
        status: "running"
        priority: "P0"
        assigned_to: "李架构"
        progress: "1/6 subtasks (VERIFIED)"
        verification:
          timestamp: "2026-02-01T23:59:00+00:00"
          test_results: "22/22 passed"
          test_file: "tests/sdf/test_state_engine.py"
        subtasks:
          - id: "SDF_DEV_001.1"
            name: "StateEngine"
            status: "completed"
            verified: true
            test_count: 22
          - id: "SDF_DEV_001.2"
            name: "SDF Model Integration"
            status: "pending"
          - id: "SDF_DEV_001.3"
            name: "Moment Estimation"
            status: "pending"
          - id: "SDF_DEV_001.4"
            name: "Trainer"
            status: "pending"
          - id: "SDF_DEV_001.5"
            name: "Oracle API"
            status: "pending"
          - id: "SDF_DEV_001.6"
            name: "Integration Test"
            status: "pending"
      - task_id: "DATA_EXPANSION_001"
        status: "running"
        priority: "P1"
        assigned_to: "王数据"
        progress: "started"
    
    # Pending Tasks
    pending_tasks:
      - task_id: "EA_DEV_001"
        status: "draft"
        priority: "P1"
        depends_on: ["SDF_DEV_001"]
      - task_id: "BASELINE_REPRO_001"
        status: "draft"
        priority: "P2"
        depends_on: ["EA_DEV_001", "DATA_EXPANSION_001"]
    
    # Milestones
    milestones:
      - name: "M1: SDF Layer Complete"
        target_date: "2026-02-17"
        status: "in_progress"
        gate: "G1"
        deliverables:
          - "state_engine.py"
          - "model.py (v3.1)"
          - "moments.py"
          - "trainer.py"
          - "oracle.py"
      - name: "M2: EA Layer Complete"
        target_date: "2026-02-23"
        status: "pending"
        gate: "G2"
        depends_on: "M1"
      - name: "M3: Full Data Pipeline"
        target_date: "2026-02-28"
        status: "pending"
        gate: "G3"
      - name: "M4: Reproducible Baseline"
        target_date: "2026-03-10"
        status: "pending"
        gate: "G4"
    
    # Repository Links
    repositories:
      main: "projects/dgsf/repo"
      legacy: "projects/dgsf/legacy/DGSF"
      specs: "projects/dgsf/specs"
    
    # Risks
    risks:
      - id: "R1"
        description: "SDF training instability"
        probability: "medium"
        impact: "high"
        mitigation: "Temperature schedule + gradient clipping"
      - id: "R2"
        description: "Data quality issues in full A-share"
        probability: "medium"
        impact: "medium"
        mitigation: "Strict data validation gates"

# =============================================================================
# Global Project Metrics
# =============================================================================
metrics:
  total_tasks_completed: 9
  total_tasks_in_progress: 1
  total_tasks_pending: 3
  last_gate_passed: "G4 (Research Plan)"
  last_gate_date: '2026-02-01'